---
- hosts: ranger_admin
  become: true
  roles:
    - ranger_admin_keystore
- hosts: ranger_plugin
  become: true
  roles:
    - ranger_plugin
- hosts: ranger_admin
  become: true
  roles:
    - import_cert

- hosts: all
  become: true
  roles:
    - all_nodes

#- hosts: app02
#  become: true
#  roles:
#    - ranger_nginx
